//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mtwpia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class List_of_ListsEntities3 : DbContext
    {
        public List_of_ListsEntities3()
            : base("name=List_of_ListsEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animated_Movies> Animated_Movies { get; set; }
        public virtual DbSet<Anime____Cartoons> Anime____Cartoons { get; set; }
        public virtual DbSet<Completed_Manga___Manwah> Completed_Manga___Manwah { get; set; }
        public virtual DbSet<Current_Anime___Cartoons> Current_Anime___Cartoons { get; set; }
        public virtual DbSet<Live_Action_Movies> Live_Action_Movies { get; set; }
        public virtual DbSet<Live_Action_TV_Shows> Live_Action_TV_Shows { get; set; }
        public virtual DbSet<Manga___Manwah> Manga___Manwah { get; set; }
        public virtual DbSet<Video_Game> Video_Game { get; set; }
    }
}
